# Generated by Django 5.1.2 on 2024-11-04 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parish',
            old_name='subcounty',
            new_name='sub_county',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='polling_station',
        ),
        migrations.RemoveField(
            model_name='pollingstation',
            name='parish',
        ),
        migrations.AlterField(
            model_name='agent',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_id',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.parish')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='village',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agents.village'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='village',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agents.village'),
            preserve_default=False,
        ),
    ]
